<a href="https://colab.research.google.com/github/ncphung1405/bai-tap/blob/main/bt_tao_ham.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
import pandas as pd
import sys
np.set_printoptions(threshold=sys.maxsize)

In [21]:
V = np.zeros((6,12))

In [22]:
V
lock = [(0,4),(0,8),
        (1,4),(1,6),(1,8),
        (2,1),(2,2),(2,4),(2,6),(2,8),
        (3,1),(3,6),(3,8),
        (4,1),(4,2),(4,3),(4,4),(4,5),(4,6),(4,8),(4,9),
        (5,4)]


done = lock + [(0,11),(1,11)]

In [24]:
reward = 0

In [25]:
for l in lock:
  V[l] = -100

In [26]:
V[0,11]= 1
V[1,11] = -1
gamma = 0.9

In [27]:
print(V)

[[   0.    0.    0.    0. -100.    0.    0.    0. -100.    0.    0.    1.]
 [   0.    0.    0.    0. -100.    0. -100.    0. -100.    0.    0.   -1.]
 [   0. -100. -100.    0. -100.    0. -100.    0. -100.    0.    0.    0.]
 [   0. -100.    0.    0.    0.    0. -100.    0. -100.    0.    0.    0.]
 [   0. -100. -100. -100. -100. -100. -100.    0. -100. -100.    0.    0.]
 [   0.    0.    0.    0. -100.    0.    0.    0.    0.    0.    0.    0.]]


In [28]:
def find_move(x,y, shape_v):
  up = (x-1, y)
  down = (x+1, y)
  left = (x, y-1)
  right = (x, y+1)

  list_move = [up, down, left, right]

  true_list_move = []
  for move in list_move:
    for stt,i in enumerate(move):
      if i < 0:
        break
      elif i >= shape_v[stt]:
        break
      if stt:
        true_list_move.append(move)
  for l in lock:
    if l in true_list_move:
      true_list_move.remove(l)
  return true_list_move

In [29]:
moves = find_move(0,7, V.shape)

In [30]:
moves

[(1, 7), (0, 6)]

In [31]:
for l in lock:
  if l in moves:
    moves.remove(l)

In [32]:
moves

[(1, 7), (0, 6)]

In [33]:
moves_02 = find_move(0,2, V.shape)

In [34]:
moves_02

[(1, 2), (0, 1), (0, 3)]

In [35]:
def other_points(input_value, list_point):
    list_a = []
    if input_value in list_point:
        for item in list_point:
            if item != input_value:
                list_a.append(item)
    else:
        print("Giá trị nhập không hợp lệ.")
    return list_a

In [36]:
def update_value(moves):
  value_range = []
  for move in moves:
    position_other_points = other_points(move,moves)
    sum_other_points = 0
    for position in position_other_points:
      point = V[position]
      sum_other_points+=point
    if (len(moves)-1):
      value = 0.8*(reward + gamma*V[move])+(0.2/(len(moves)-1))*(2*reward + gamma*sum_other_points)
      value_range.append(value)
    else:
      value = reward + gamma*V[move]
      value_range.append(value)
  return max(value_range)

In [37]:
for stt in range(30):
  print(f"lần lặp: {stt+1}")
  for i, row in enumerate(V):
    #print(i)
    for j, _ in enumerate(row):
      if (i,j) not in done:
        moves = find_move(i,j, V.shape)
        V[i,j] = update_value(moves)
  rounded_array = np.round(V, 4)
  np.set_printoptions(suppress=True)

  display(pd.DataFrame(rounded_array))

lần lặp: 1


0      1      2      3      4      5      6    7      8      9       10  \
0  0.0    0.0    0.0    0.0 -100.0    0.0    0.0  0.0 -100.0    0.0  0.7200   
1  0.0    0.0    0.0    0.0 -100.0    0.0 -100.0  0.0 -100.0    0.0  0.4584   
2  0.0 -100.0 -100.0    0.0 -100.0    0.0 -100.0  0.0 -100.0    0.0  0.3300   
3  0.0 -100.0    0.0    0.0    0.0    0.0 -100.0  0.0 -100.0    0.0  0.2376   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0  0.0 -100.0 -100.0  0.1711   
5  0.0    0.0    0.0    0.0 -100.0    0.0    0.0  0.0    0.0    0.0  0.1232   

       11  
0  1.0000  
1 -1.0000  
2  0.1476  
3  0.1844  
4  0.1482  
5  0.1288

lần lặp: 2


0      1      2      3      4      5      6    7      8         9   \
0  0.0    0.0    0.0    0.0 -100.0    0.0    0.0  0.0 -100.0    0.5184   
1  0.0    0.0    0.0    0.0 -100.0    0.0 -100.0  0.0 -100.0    0.4145   
2  0.0 -100.0 -100.0    0.0 -100.0    0.0 -100.0  0.0 -100.0    0.3281   
3  0.0 -100.0    0.0    0.0    0.0    0.0 -100.0  0.0 -100.0    0.2790   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0  0.0 -100.0 -100.0000   
5  0.0    0.0    0.0    0.0 -100.0    0.0    0.0  0.0    0.0    0.0887   

       10      11  
0  0.8079  1.0000  
1  0.5664 -1.0000  
2  0.4506  0.2510  
3  0.3625  0.2969  
4  0.2854  0.2511  
5  0.2251  0.2213

lần lặp: 3


0      1      2      3      4      5      6    7         8         9   \
0  0.0    0.0    0.0    0.0 -100.0    0.0    0.0  0.0 -100.0000    0.6563   
1  0.0    0.0    0.0    0.0 -100.0    0.0 -100.0  0.0 -100.0000    0.5530   
2  0.0 -100.0 -100.0    0.0 -100.0    0.0 -100.0  0.0 -100.0000    0.4639   
3  0.0 -100.0    0.0    0.0    0.0    0.0 -100.0  0.0 -100.0000    0.3992   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0  0.0 -100.0000 -100.0000   
5  0.0    0.0    0.0    0.0 -100.0    0.0    0.0  0.0    0.0639    0.1736   

       10      11  
0  0.8300  1.0000  
1  0.5978 -1.0000  
2  0.4951  0.2932  
3  0.4154  0.3480  
4  0.3419  0.3013  
5  0.2817  0.2676

lần lặp: 4


0      1      2      3      4      5      6      7         8         9   \
0  0.0    0.0    0.0    0.0 -100.0    0.0    0.0  0.000 -100.0000    0.6972   
1  0.0    0.0    0.0    0.0 -100.0    0.0 -100.0  0.000 -100.0000    0.5975   
2  0.0 -100.0 -100.0    0.0 -100.0    0.0 -100.0  0.000 -100.0000    0.5107   
3  0.0 -100.0    0.0    0.0    0.0    0.0 -100.0  0.000 -100.0000    0.4425   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0  0.000 -100.0000 -100.0000   
5  0.0    0.0    0.0    0.0 -100.0    0.0    0.0  0.046    0.1332    0.2268   

       10      11  
0  0.8366  1.0000  
1  0.6079 -1.0000  
2  0.5108  0.3091  
3  0.4357  0.3687  
4  0.3662  0.3225  
5  0.3082  0.2877

lần lặp: 5


0      1      2      3      4      5         6       7         8   \
0  0.0    0.0    0.0    0.0 -100.0    0.0    0.0000  0.0000 -100.0000   
1  0.0    0.0    0.0    0.0 -100.0    0.0 -100.0000  0.0000 -100.0000   
2  0.0 -100.0 -100.0    0.0 -100.0    0.0 -100.0000  0.0000 -100.0000   
3  0.0 -100.0    0.0    0.0    0.0    0.0 -100.0000  0.0000 -100.0000   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0000  0.0331 -100.0000   
5  0.0    0.0    0.0    0.0 -100.0    0.0    0.0331  0.1019    0.1816   

         9       10      11  
0    0.7099  0.8386  1.0000  
1    0.6118  0.6111 -1.0000  
2    0.5263  0.5163  0.3149  
3    0.4574  0.4433  0.3765  
4 -100.0000  0.3759  0.3308  
5    0.2546  0.3195  0.2957

lần lặp: 6


0      1      2      3      4         5         6       7         8   \
0  0.0    0.0    0.0    0.0 -100.0    0.0000    0.0000  0.0000 -100.0000   
1  0.0    0.0    0.0    0.0 -100.0    0.0000 -100.0000  0.0000 -100.0000   
2  0.0 -100.0 -100.0    0.0 -100.0    0.0000 -100.0000  0.0000 -100.0000   
3  0.0 -100.0    0.0    0.0    0.0    0.0000 -100.0000  0.0238 -100.0000   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.0000 -100.0000  0.0776 -100.0000   
5  0.0    0.0    0.0    0.0 -100.0    0.0298    0.0787  0.1449    0.2094   

         9       10      11  
0    0.7139  0.8393  1.0000  
1    0.6164  0.6122 -1.0000  
2    0.5314  0.5182  0.3170  
3    0.4624  0.4460  0.3794  
4 -100.0000  0.3796  0.3341  
5    0.2677  0.3240  0.2989

lần lặp: 7


0      1      2      3      4         5         6       7         8   \
0  0.0    0.0    0.0    0.0 -100.0    0.0000    0.0000  0.0000 -100.0000   
1  0.0    0.0    0.0    0.0 -100.0    0.0000 -100.0000  0.0000 -100.0000   
2  0.0 -100.0 -100.0    0.0 -100.0    0.0000 -100.0000  0.0172 -100.0000   
3  0.0 -100.0    0.0    0.0    0.0    0.0000 -100.0000  0.0590 -100.0000   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.0000 -100.0000  0.1149 -100.0000   
5  0.0    0.0    0.0    0.0 -100.0    0.0709    0.1171  0.1716    0.2236   

         9       10      11  
0    0.7152  0.8395  1.0000  
1    0.6179  0.6126 -1.0000  
2    0.5331  0.5188  0.3177  
3    0.4641  0.4469  0.3805  
4 -100.0000  0.3810  0.3355  
5    0.2736  0.3259  0.3002

lần lặp: 8


0      1      2      3      4         5         6       7         8   \
0  0.0    0.0    0.0    0.0 -100.0    0.0000    0.0000  0.0000 -100.0000   
1  0.0    0.0    0.0    0.0 -100.0    0.0000 -100.0000  0.0124 -100.0000   
2  0.0 -100.0 -100.0    0.0 -100.0    0.0000 -100.0000  0.0447 -100.0000   
3  0.0 -100.0    0.0    0.0    0.0    0.0000 -100.0000  0.0908 -100.0000   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.0000 -100.0000  0.1399 -100.0000   
5  0.0    0.0    0.0    0.0 -100.0    0.1053    0.1425  0.1864    0.2305   

         9       10      11  
0    0.7156  0.8395  1.0000  
1    0.6184  0.6127 -1.0000  
2    0.5337  0.5190  0.3180  
3    0.4647  0.4473  0.3809  
4 -100.0000  0.3816  0.3360  
5    0.2761  0.3266  0.3007

lần lặp: 9


0      1      2      3      4         5         6       7         8   \
0  0.0    0.0    0.0    0.0 -100.0    0.0000    0.0000  0.0089 -100.0000   
1  0.0    0.0    0.0    0.0 -100.0    0.0000 -100.0000  0.0338 -100.0000   
2  0.0 -100.0 -100.0    0.0 -100.0    0.0000 -100.0000  0.0714 -100.0000   
3  0.0 -100.0    0.0    0.0    0.0    0.0000 -100.0000  0.1136 -100.0000   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.0000 -100.0000  0.1547 -100.0000   
5  0.0    0.0    0.0    0.0 -100.0    0.1283    0.1573  0.1941    0.2337   

         9       10      11  
0    0.7158  0.8396  1.0000  
1    0.6185  0.6127 -1.0000  
2    0.5339  0.5191  0.3180  
3    0.4649  0.4474  0.3810  
4 -100.0000  0.3818  0.3362  
5    0.2772  0.3269  0.3009

lần lặp: 10


0      1      2      3      4         5         6       7         8   \
0  0.0    0.0    0.0    0.0 -100.0    0.0000    0.0064  0.0255 -100.0000   
1  0.0    0.0    0.0    0.0 -100.0    0.0000 -100.0000  0.0560 -100.0000   
2  0.0 -100.0 -100.0    0.0 -100.0    0.0000 -100.0000  0.0919 -100.0000   
3  0.0 -100.0    0.0    0.0    0.0    0.0000 -100.0000  0.1279 -100.0000   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.0000 -100.0000  0.1627 -100.0000   
5  0.0    0.0    0.0    0.0 -100.0    0.1416    0.1652  0.1978    0.2352   

         9       10      11  
0    0.7158  0.8396  1.0000  
1    0.6186  0.6128 -1.0000  
2    0.5339  0.5191  0.3181  
3    0.4650  0.4474  0.3811  
4 -100.0000  0.3818  0.3363  
5    0.2777  0.3270  0.3010

lần lặp: 11


0      1      2      3      4         5         6       7         8   \
0  0.0    0.0    0.0    0.0 -100.0    0.0046    0.0192  0.0438 -100.0000   
1  0.0    0.0    0.0    0.0 -100.0    0.0033 -100.0000  0.0740 -100.0000   
2  0.0 -100.0 -100.0    0.0 -100.0    0.0024 -100.0000  0.1054 -100.0000   
3  0.0 -100.0    0.0    0.0    0.0    0.0017 -100.0000  0.1362 -100.0000   
4  0.0 -100.0 -100.0 -100.0 -100.0 -100.0000 -100.0000  0.1669 -100.0000   
5  0.0    0.0    0.0    0.0 -100.0    0.1487    0.1692  0.1996    0.2359   

         9       10      11  
0    0.7158  0.8396  1.0000  
1    0.6186  0.6128 -1.0000  
2    0.5340  0.5192  0.3181  
3    0.4650  0.4475  0.3811  
4 -100.0000  0.3819  0.3363  
5    0.2779  0.3270  0.3010

lần lặp: 12


0      1      2      3         4         5         6       7         8   \
0  0.0    0.0    0.0    0.0 -100.0000    0.0144    0.0341  0.0594 -100.0000   
1  0.0    0.0    0.0    0.0 -100.0000    0.0108 -100.0000  0.0866 -100.0000   
2  0.0 -100.0 -100.0    0.0 -100.0000    0.0081 -100.0000  0.1136 -100.0000   
3  0.0 -100.0    0.0    0.0    0.0012    0.0060 -100.0000  0.1406 -100.0000   
4  0.0 -100.0 -100.0 -100.0 -100.0000 -100.0000 -100.0000  0.1690 -100.0000   
5  0.0    0.0    0.0    0.0 -100.0000    0.1523    0.1711  0.2004    0.2362   

         9       10      11  
0    0.7158  0.8396  1.0000  
1    0.6186  0.6128 -1.0000  
2    0.5340  0.5192  0.3181  
3    0.4650  0.4475  0.3811  
4 -100.0000  0.3819  0.3363  
5    0.2780  0.3271  0.3010

lần lặp: 13


0      1      2         3         4         5         6       7   \
0  0.0    0.0    0.0    0.0000 -100.0000    0.0265    0.0476  0.0709   
1  0.0    0.0    0.0    0.0000 -100.0000    0.0205 -100.0000  0.0946   
2  0.0 -100.0 -100.0    0.0000 -100.0000    0.0159 -100.0000  0.1183   
3  0.0 -100.0    0.0    0.0009    0.0045    0.0122 -100.0000  0.1430   
4  0.0 -100.0 -100.0 -100.0000 -100.0000 -100.0000 -100.0000  0.1701   
5  0.0    0.0    0.0    0.0000 -100.0000    0.1540    0.1720  0.2008   

         8         9       10      11  
0 -100.0000    0.7158  0.8396  1.0000  
1 -100.0000    0.6186  0.6128 -1.0000  
2 -100.0000    0.5340  0.5192  0.3181  
3 -100.0000    0.4650  0.4475  0.3811  
4 -100.0000 -100.0000  0.3819  0.3363  
5    0.2363    0.2780  0.3271  0.3010

lần lặp: 14


0      1         2         3         4         5         6       7   \
0  0.0    0.0    0.0000    0.0000 -100.0000    0.0380    0.0579  0.0785   
1  0.0    0.0    0.0000    0.0000 -100.0000    0.0302 -100.0000  0.0993   
2  0.0 -100.0 -100.0000    0.0006 -100.0000    0.0239 -100.0000  0.1208   
3  0.0 -100.0    0.0008    0.0034    0.0094    0.0189 -100.0000  0.1442   
4  0.0 -100.0 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000  0.1705   
5  0.0    0.0    0.0000    0.0000 -100.0000    0.1548    0.1725  0.2010   

         8         9       10      11  
0 -100.0000    0.7158  0.8396  1.0000  
1 -100.0000    0.6186  0.6128 -1.0000  
2 -100.0000    0.5340  0.5192  0.3181  
3 -100.0000    0.4650  0.4475  0.3811  
4 -100.0000 -100.0000  0.3819  0.3364  
5    0.2364    0.2780  0.3271  0.3010

lần lặp: 15


0      1        2         3         4         5         6       7   \
0  0.0    0.0    0.000    0.0000 -100.0000    0.0471    0.0650  0.0832   
1  0.0    0.0    0.000    0.0005 -100.0000    0.0382 -100.0000  0.1020   
2  0.0 -100.0 -100.000    0.0025 -100.0000    0.0309 -100.0000  0.1222   
3  0.0 -100.0    0.003    0.0073    0.0149    0.0250 -100.0000  0.1448   
4  0.0 -100.0 -100.000 -100.0000 -100.0000 -100.0000 -100.0000  0.1708   
5  0.0    0.0    0.000    0.0000 -100.0000    0.1552    0.1727  0.2011   

         8         9       10      11  
0 -100.0000    0.7158  0.8396  1.0000  
1 -100.0000    0.6186  0.6128 -1.0000  
2 -100.0000    0.5340  0.5192  0.3181  
3 -100.0000    0.4650  0.4475  0.3811  
4 -100.0000 -100.0000  0.3819  0.3364  
5    0.2364    0.2780  0.3271  0.3010

lần lặp: 16


0      1         2         3         4         5         6       7   \
0  0.0    0.0    0.0000    0.0003 -100.0000    0.0537    0.0696  0.0859   
1  0.0    0.0    0.0003    0.0019 -100.0000    0.0442 -100.0000  0.1034   
2  0.0 -100.0 -100.0000    0.0056 -100.0000    0.0363 -100.0000  0.1229   
3  0.0 -100.0    0.0066    0.0119    0.0201    0.0298 -100.0000  0.1451   
4  0.0 -100.0 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000  0.1709   
5  0.0    0.0    0.0000    0.0000 -100.0000    0.1554    0.1728  0.2011   

         8         9       10      11  
0 -100.0000    0.7158  0.8396  1.0000  
1 -100.0000    0.6186  0.6128 -1.0000  
2 -100.0000    0.5340  0.5192  0.3181  
3 -100.0000    0.4650  0.4475  0.3811  
4 -100.0000 -100.0000  0.3819  0.3364  
5    0.2364    0.2780  0.3271  0.3010

lần lặp: 17


0         1         2         3         4         5         6       7   \
0  0.0    0.0000    0.0003    0.0014 -100.0000    0.0580    0.0723  0.0875   
1  0.0    0.0002    0.0014    0.0043 -100.0000    0.0483 -100.0000  0.1042   
2  0.0 -100.0000 -100.0000    0.0093 -100.0000    0.0402 -100.0000  0.1232   
3  0.0 -100.0000    0.0107    0.0163    0.0244    0.0333 -100.0000  0.1452   
4  0.0 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000  0.1710   
5  0.0    0.0000    0.0000    0.0000 -100.0000    0.1555    0.1728  0.2011   

         8         9       10      11  
0 -100.0000    0.7158  0.8396  1.0000  
1 -100.0000    0.6186  0.6128 -1.0000  
2 -100.0000    0.5340  0.5192  0.3181  
3 -100.0000    0.4650  0.4475  0.3811  
4 -100.0000 -100.0000  0.3819  0.3364  
5    0.2364    0.2780  0.3271  0.3010

lần lặp: 18


0         1         2         3         4         5         6       7   \
0  0.0000    0.0002    0.0012    0.0033 -100.0000    0.0608    0.0739  0.0883   
1  0.0002    0.0010    0.0033    0.0073 -100.0000    0.0510 -100.0000  0.1046   
2  0.0001 -100.0000 -100.0000    0.0130 -100.0000    0.0427 -100.0000  0.1234   
3  0.0001 -100.0000    0.0146    0.0200    0.0276    0.0357 -100.0000  0.1453   
4  0.0001 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000  0.1710   
5  0.0000    0.0000    0.0000    0.0000 -100.0000    0.1555    0.1728  0.2011   

         8         9       10      11  
0 -100.0000    0.7158  0.8396  1.0000  
1 -100.0000    0.6186  0.6128 -1.0000  
2 -100.0000    0.5340  0.5192  0.3181  
3 -100.0000    0.4650  0.4475  0.3811  
4 -100.0000 -100.0000  0.3819  0.3364  
5    0.2364    0.2780  0.3271  0.3010

lần lặp: 19


0         1         2         3         4         5         6       7   \
0  0.0002    0.0009    0.0027    0.0057 -100.0000    0.0624    0.0748  0.0888   
1  0.0008    0.0025    0.0057    0.0104 -100.0000    0.0526 -100.0000  0.1048   
2  0.0006 -100.0000 -100.0000    0.0163 -100.0000    0.0443 -100.0000  0.1235   
3  0.0004 -100.0000    0.0180    0.0230    0.0298    0.0373 -100.0000  0.1453   
4  0.0003 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000  0.1710   
5  0.0002    0.0002    0.0001    0.0001 -100.0000    0.1555    0.1728  0.2012   

         8         9       10      11  
0 -100.0000    0.7158  0.8396  1.0000  
1 -100.0000    0.6186  0.6128 -1.0000  
2 -100.0000    0.5340  0.5192  0.3181  
3 -100.0000    0.4650  0.4475  0.3811  
4 -100.0000 -100.0000  0.3819  0.3364  
5    0.2364    0.2780  0.3271  0.3010

lần lặp: 20


0         1         2         3         4         5         6       7   \
0  0.0008    0.0023    0.0049    0.0084 -100.0000    0.0634    0.0753  0.0890   
1  0.0019    0.0045    0.0083    0.0132 -100.0000    0.0536 -100.0000  0.1049   
2  0.0015 -100.0000 -100.0000    0.0189 -100.0000    0.0453 -100.0000  0.1235   
3  0.0011 -100.0000    0.0207    0.0250    0.0313    0.0383 -100.0000  0.1453   
4  0.0008 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000  0.1710   
5  0.0006    0.0005    0.0004    0.0003 -100.0000    0.1555    0.1728  0.2012   

         8         9       10      11  
0 -100.0000    0.7158  0.8396  1.0000  
1 -100.0000    0.6186  0.6128 -1.0000  
2 -100.0000    0.5340  0.5192  0.3181  
3 -100.0000    0.4650  0.4475  0.3811  
4 -100.0000 -100.0000  0.3819  0.3364  
5    0.2364    0.2781  0.3271  0.3010

lần lặp: 21


0         1         2         3         4         5         6       7   \
0  0.0020    0.0041    0.0071    0.0108 -100.0000    0.0639    0.0756  0.0892   
1  0.0035    0.0067    0.0108    0.0156 -100.0000    0.0542 -100.0000  0.1050   
2  0.0028 -100.0000 -100.0000    0.0208 -100.0000    0.0459 -100.0000  0.1235   
3  0.0021 -100.0000    0.0225    0.0265    0.0323    0.0388 -100.0000  0.1454   
4  0.0017 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000  0.1710   
5  0.0013    0.0010    0.0008    0.0007 -100.0000    0.1555    0.1728  0.2012   

         8         9       10      11  
0 -100.0000    0.7158  0.8396  1.0000  
1 -100.0000    0.6186  0.6128 -1.0000  
2 -100.0000    0.5340  0.5192  0.3181  
3 -100.0000    0.4650  0.4475  0.3811  
4 -100.0000 -100.0000  0.3819  0.3364  
5    0.2364    0.2781  0.3271  0.3010

lần lặp: 22


0         1         2         3         4         5         6       7   \
0  0.0036    0.0061    0.0093    0.0129 -100.0000    0.0642    0.0757  0.0892   
1  0.0054    0.0088    0.0128    0.0173 -100.0000    0.0545 -100.0000  0.1050   
2  0.0043 -100.0000 -100.0000    0.0222 -100.0000    0.0462 -100.0000  0.1236   
3  0.0034 -100.0000    0.0238    0.0274    0.0329    0.0392 -100.0000  0.1454   
4  0.0027 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000  0.1710   
5  0.0021    0.0016    0.0013    0.0012 -100.0000    0.1555    0.1728  0.2012   

         8         9       10      11  
0 -100.0000    0.7158  0.8396  1.0000  
1 -100.0000    0.6186  0.6128 -1.0000  
2 -100.0000    0.5340  0.5192  0.3181  
3 -100.0000    0.4650  0.4475  0.3811  
4 -100.0000 -100.0000  0.3819  0.3364  
5    0.2364    0.2781  0.3271  0.3010

lần lặp: 23


0         1         2         3         4         5         6       7   \
0  0.0053    0.0080    0.0111    0.0145 -100.0000    0.0643    0.0758  0.0893   
1  0.0072    0.0106    0.0144    0.0186 -100.0000    0.0546 -100.0000  0.1050   
2  0.0058 -100.0000 -100.0000    0.0231 -100.0000    0.0464 -100.0000  0.1236   
3  0.0046 -100.0000    0.0247    0.0280    0.0333    0.0394 -100.0000  0.1454   
4  0.0037 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000  0.1710   
5  0.0030    0.0024    0.0019    0.0017 -100.0000    0.1555    0.1728  0.2012   

         8         9       10      11  
0 -100.0000    0.7158  0.8396  1.0000  
1 -100.0000    0.6186  0.6128 -1.0000  
2 -100.0000    0.5340  0.5192  0.3181  
3 -100.0000    0.4650  0.4475  0.3811  
4 -100.0000 -100.0000  0.3819  0.3364  
5    0.2364    0.2781  0.3271  0.3010

lần lặp: 24


0         1         2         3         4         5         6       7   \
0  0.0070    0.0096    0.0126    0.0156 -100.0000    0.0644    0.0759  0.0893   
1  0.0088    0.0120    0.0156    0.0194 -100.0000    0.0547 -100.0000  0.1050   
2  0.0072 -100.0000 -100.0000    0.0236 -100.0000    0.0465 -100.0000  0.1236   
3  0.0058 -100.0000    0.0252    0.0283    0.0335    0.0395 -100.0000  0.1454   
4  0.0047 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000  0.1710   
5  0.0038    0.0031    0.0025    0.0023 -100.0000    0.1555    0.1728  0.2012   

         8         9       10      11  
0 -100.0000    0.7158  0.8396  1.0000  
1 -100.0000    0.6186  0.6128 -1.0000  
2 -100.0000    0.5340  0.5192  0.3181  
3 -100.0000    0.4650  0.4475  0.3811  
4 -100.0000 -100.0000  0.3819  0.3364  
5    0.2364    0.2781  0.3271  0.3010

lần lặp: 25


0         1         2         3         4         5         6       7   \
0  0.0085    0.0109    0.0136    0.0164 -100.0000    0.0645    0.0759  0.0893   
1  0.0101    0.0131    0.0164    0.0200 -100.0000    0.0548 -100.0000  0.1050   
2  0.0083 -100.0000 -100.0000    0.0240 -100.0000    0.0466 -100.0000  0.1236   
3  0.0068 -100.0000    0.0255    0.0286    0.0336    0.0396 -100.0000  0.1454   
4  0.0056 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000  0.1710   
5  0.0046    0.0038    0.0031    0.0028 -100.0000    0.1555    0.1728  0.2012   

         8         9       10      11  
0 -100.0000    0.7158  0.8396  1.0000  
1 -100.0000    0.6186  0.6128 -1.0000  
2 -100.0000    0.5340  0.5192  0.3181  
3 -100.0000    0.4650  0.4475  0.3811  
4 -100.0000 -100.0000  0.3819  0.3364  
5    0.2364    0.2781  0.3271  0.3010

lần lặp: 26


0         1         2         3         4         5         6       7   \
0  0.0097    0.0119    0.0144    0.0170 -100.0000    0.0645    0.0759  0.0893   
1  0.0111    0.0139    0.0169    0.0203 -100.0000    0.0548 -100.0000  0.1050   
2  0.0092 -100.0000 -100.0000    0.0242 -100.0000    0.0466 -100.0000  0.1236   
3  0.0076 -100.0000    0.0257    0.0287    0.0337    0.0396 -100.0000  0.1454   
4  0.0063 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000  0.1710   
5  0.0052    0.0043    0.0036    0.0033 -100.0000    0.1555    0.1728  0.2012   

         8         9       10      11  
0 -100.0000    0.7158  0.8396  1.0000  
1 -100.0000    0.6186  0.6128 -1.0000  
2 -100.0000    0.5340  0.5192  0.3181  
3 -100.0000    0.4650  0.4475  0.3811  
4 -100.0000 -100.0000  0.3819  0.3364  
5    0.2364    0.2781  0.3271  0.3010

lần lặp: 27


0         1         2         3         4         5         6       7   \
0  0.0105    0.0126    0.0149    0.0173 -100.0000    0.0645    0.0759  0.0893   
1  0.0118    0.0144    0.0173    0.0205 -100.0000    0.0548 -100.0000  0.1050   
2  0.0098 -100.0000 -100.0000    0.0243 -100.0000    0.0466 -100.0000  0.1236   
3  0.0082 -100.0000    0.0258    0.0287    0.0337    0.0396 -100.0000  0.1454   
4  0.0069 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000  0.1710   
5  0.0057    0.0048    0.0040    0.0036 -100.0000    0.1555    0.1728  0.2012   

         8         9       10      11  
0 -100.0000    0.7158  0.8396  1.0000  
1 -100.0000    0.6186  0.6128 -1.0000  
2 -100.0000    0.5340  0.5192  0.3181  
3 -100.0000    0.4650  0.4475  0.3811  
4 -100.0000 -100.0000  0.3819  0.3364  
5    0.2364    0.2781  0.3271  0.3010

lần lặp: 28


0         1         2         3         4         5         6       7   \
0  0.0112    0.0130    0.0152    0.0175 -100.0000    0.0645    0.0759  0.0893   
1  0.0122    0.0147    0.0175    0.0207 -100.0000    0.0548 -100.0000  0.1050   
2  0.0103 -100.0000 -100.0000    0.0244 -100.0000    0.0466 -100.0000  0.1236   
3  0.0086 -100.0000    0.0259    0.0288    0.0337    0.0396 -100.0000  0.1454   
4  0.0073 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000  0.1710   
5  0.0061    0.0051    0.0043    0.0039 -100.0000    0.1555    0.1728  0.2012   

         8         9       10      11  
0 -100.0000    0.7158  0.8396  1.0000  
1 -100.0000    0.6186  0.6128 -1.0000  
2 -100.0000    0.5340  0.5192  0.3181  
3 -100.0000    0.4650  0.4475  0.3811  
4 -100.0000 -100.0000  0.3819  0.3364  
5    0.2364    0.2781  0.3271  0.3010

lần lặp: 29


0         1         2         3         4         5         6       7   \
0  0.0116    0.0133    0.0154    0.0177 -100.0000    0.0645    0.0759  0.0893   
1  0.0126    0.0149    0.0176    0.0208 -100.0000    0.0548 -100.0000  0.1050   
2  0.0106 -100.0000 -100.0000    0.0245 -100.0000    0.0466 -100.0000  0.1236   
3  0.0089 -100.0000    0.0259    0.0288    0.0337    0.0396 -100.0000  0.1454   
4  0.0075 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000  0.1710   
5  0.0063    0.0053    0.0045    0.0041 -100.0000    0.1555    0.1728  0.2012   

         8         9       10      11  
0 -100.0000    0.7158  0.8396  1.0000  
1 -100.0000    0.6186  0.6128 -1.0000  
2 -100.0000    0.5340  0.5192  0.3181  
3 -100.0000    0.4650  0.4475  0.3811  
4 -100.0000 -100.0000  0.3819  0.3364  
5    0.2364    0.2781  0.3271  0.3010

lần lặp: 30


0         1         2         3         4         5         6       7   \
0  0.0118    0.0135    0.0155    0.0177 -100.0000    0.0645    0.0759  0.0893   
1  0.0128    0.0150    0.0177    0.0208 -100.0000    0.0548 -100.0000  0.1050   
2  0.0108 -100.0000 -100.0000    0.0245 -100.0000    0.0466 -100.0000  0.1236   
3  0.0091 -100.0000    0.0259    0.0288    0.0337    0.0396 -100.0000  0.1454   
4  0.0077 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000 -100.0000  0.1710   
5  0.0065    0.0055    0.0047    0.0042 -100.0000    0.1555    0.1728  0.2012   

         8         9       10      11  
0 -100.0000    0.7158  0.8396  1.0000  
1 -100.0000    0.6186  0.6128 -1.0000  
2 -100.0000    0.5340  0.5192  0.3181  
3 -100.0000    0.4650  0.4475  0.3811  
4 -100.0000 -100.0000  0.3819  0.3364  
5    0.2364    0.2781  0.3271  0.3010